from typing import Literal, Optional
from pydantic import BaseModel, Field, field_validator


# ─────────────────────────────────────────────────────────────────────────────
# Request / Input models
# ─────────────────────────────────────────────────────────────────────────────

class StoryRequest(BaseModel):
    main_character: str = Field(
        default="Benny the Brave Bunny",
        description="Name and brief description of the main character",
    )
    supporting_characters: list[str] = Field(
        default_factory=lambda: ["Rosie the Fox", "Oliver the Owl"],
        description="Names and descriptions of supporting characters",
    )
    setting: str = Field(
        default="A magical forest with talking trees and glowing fireflies",
        description="Primary setting of the story",
    )
    moral: str = Field(
        default="True courage means helping others even when you're scared",
        description="The moral lesson to weave into the story",
    )
    main_problem: str = Field(
        default="A mysterious fog has covered the forest, and the animals can't find their way home",
        description="The central conflict or challenge the main character faces",
    )
    additional_details: Optional[str] = Field(
        default="Include a scene where the characters work together to solve a puzzle",
        description="Any additional plot details, themes, or scenes to include",
    )
    wikipedia_topic: Optional[str] = Field(
        default=None,
        description="Optional Wikipedia topic to base the story on (e.g. 'Marie Curie', 'Moon landing')",
    )
    wikipedia_mode: Literal["full", "influence"] = Field(
        default="influence",
        description=(
            "'full' = Wikipedia controls the entire story; "
            "'influence' = Wikipedia provides background context blended with the user's story parameters"
        ),
    )

    # Bonus content flags — drive the optional fan-out agents
    include_look_and_find: bool = Field(
        default=True,
        description="When True, generates a Look & Find activity page at the end of the book",
    )
    include_character_glossary: bool = Field(
        default=True,
        description="When True, generates a Character Glossary page at the end of the book",
    )

    # Workflow control
    enable_story_reviewer: bool = Field(
        default=True,
        description="When True, runs the story reviewer agent for quality review and potential revision loops",
    )

    # Server-managed session id for this generation run.  Set by StoryGenerator
    # before the workflow starts; used by ArtDirector to write per-session
    # draft images and surfaced to the client so it can echo it back on save.
    session_id: Optional[str] = Field(
        default=None,
        description="Server-assigned per-generation session id (do not set from the client).",
    )


# ─────────────────────────────────────────────────────────────────────────────
# Intermediate workflow data models
# ─────────────────────────────────────────────────────────────────────────────

class PageOutline(BaseModel):
    page_number: int
    scene_summary: str
    characters_present: list[str]
    emotional_tone: str
    plot_point: str  # what story milestone happens on this page


class StoryOutline(BaseModel):
    title: str
    target_pages: int = Field(ge=8, le=10)
    # Maps character name → detailed visual description for image consistency
    character_descriptions: dict[str, str]
    plot_summary: str
    page_outlines: list[PageOutline]
    # Populated during revision cycles
    revision_instructions: Optional[str] = None


class StoryPage(BaseModel):
    page_number: int
    text: str  # narrative text displayed on the page
    scene_description: str  # detailed visual description for the illustrator
    characters_present: list[str]
    emotional_tone: str
    image_prompt: str  # prompt sent to the image generation model
    image_url: Optional[str] = None  # filled in by ArtDirectorExecutor


class StoryDraft(BaseModel):
    title: str
    pages: list[StoryPage]
    moral_summary: str  # final page / closing moral statement
    cover_image_url: Optional[str] = None     # generated by ArtDirectorExecutor
    the_end_image_url: Optional[str] = None   # generated by ArtDirectorExecutor


# ─────────────────────────────────────────────────────────────────────────────
# Structured-output DTO for the StoryArchitect agent.
#
# StoryDraft / StoryPage above carry image-URL fields populated by
# ArtDirectorExecutor *after* the LLM runs. Under strict json_schema
# response_format mode, passing StoryDraft directly would force the model to
# emit `null` for those fields (or, worse, hallucinate URLs). The DTOs below
# are the LLM's actual output shape; story_architect.py converts to
# StoryDraft after the call so ArtDirector can fill in the URLs downstream.
# ─────────────────────────────────────────────────────────────────────────────


class StoryPageDraft(BaseModel):
    page_number: int
    text: str
    scene_description: str
    characters_present: list[str]
    emotional_tone: str
    image_prompt: str


class StoryArchitectOutput(BaseModel):
    title: str
    pages: list[StoryPageDraft]
    moral_summary: str


# StoryOutline (above) carries character_descriptions as a ``dict[str, str]``
# because every consumer (orchestrator, story_architect, story_reviewer,
# art_director, character_glossary) reads it that way. Strict ``json_schema``
# response_format mode does NOT support open-ended dict types — every object
# in the schema must declare a fixed property set with ``additionalProperties:
# false``. The DTO below is the LLM's actual output shape; orchestrator.py
# converts to StoryOutline (with the dict view) after the call.


class CharacterDescription(BaseModel):
    name: str
    description: str


class StoryOutlineDraft(BaseModel):
    title: str
    target_pages: int = Field(ge=8, le=10)
    character_descriptions: list[CharacterDescription]
    plot_summary: str
    page_outlines: list[PageOutline]


class ReviewIssue(BaseModel):
    # Pydantic will coerce strings like "3" to int 3. We additionally accept
    # any non-numeric label (e.g. "Cover", "All pages") as None so the LLM
    # can flag whole-story or cover issues without breaking validation.
    page_number: Optional[int] = None
    category: str  # "character_consistency" | "narrative_coherence" | "age_appropriateness" | "moral_integration" | "art_text_alignment"
    severity: str = "medium"  # "high" | "medium" | "low"
    description: str

    @field_validator("page_number", mode="before")
    @classmethod
    def _coerce_page_number(cls, v):  # noqa: ANN001
        if v is None or isinstance(v, int):
            return v
        if isinstance(v, str):
            s = v.strip()
            if not s:
                return None
            try:
                return int(s)
            except ValueError:
                # "Cover", "All pages", "the end", etc. → whole-story issue
                return None
        return v


class ReviewResult(BaseModel):
    approved: bool
    issues: list[ReviewIssue]
    revision_instructions: str  # actionable feedback for the Orchestrator
    # Per-category pass/fail booleans force the reviewer to commit per axis
    # rather than issue a blanket approval. Default True so older payloads
    # (e.g. cached reviews from prior runs) keep validating.
    character_consistency_pass: bool = True
    narrative_coherence_pass: bool = True
    age_appropriateness_pass: bool = True
    moral_integration_pass: bool = True
    art_text_alignment_pass: bool = True


# ─────────────────────────────────────────────────────────────────────────────
# Bonus content models (produced by fan-out agents)
# ─────────────────────────────────────────────────────────────────────────────

class LookAndFindItem(BaseModel):
    page_number: int                  # which story page the item appears on
    item_name: str                    # short name, e.g. "glowing lantern"
    item_description: str             # child-friendly description of what to find
    hint: Optional[str] = None        # optional visual hint for younger readers


class LookAndFindActivity(BaseModel):
    instructions: str                 # opening sentence for the activity page
    items: list[LookAndFindItem]      # 3–5 things to find across the story pages


class CharacterGlossaryEntry(BaseModel):
    name: str                         # character name
    description: str                  # short, fun description suitable for ages 5–8
    role: str                         # e.g. "main character", "best friend", "wise mentor"


class CharacterGlossary(BaseModel):
    entries: list[CharacterGlossaryEntry]


# ─────────────────────────────────────────────────────────────────────────────
# Final output model
# ─────────────────────────────────────────────────────────────────────────────

class StoryResponse(BaseModel):
    title: str
    pages: list[StoryPage]
    moral_summary: str
    cover_image_url: Optional[str] = None
    the_end_image_url: Optional[str] = None
    review_notes: str  # summary from the reviewer (even if approved)
    revision_rounds: int  # how many revision cycles were needed
    look_and_find: Optional[LookAndFindActivity] = None   # populated by LookAndFindActivityExecutor
    character_glossary: Optional[CharacterGlossary] = None  # populated by CharacterGlossaryExecutor


# ─────────────────────────────────────────────────────────────────────────────
# SSE progress event model
# ─────────────────────────────────────────────────────────────────────────────

class ProgressEvent(BaseModel):
    executor_id: str
    status: str  # "started" | "working" | "completed" | "revision"
    message: str
    detail: Optional[str] = None
